FoodBasketApp/Entities/FoodItem.cs
using FoodBasketApp.Entities;

namespace FoodBasketApp.Entities
{
    public class FoodItem
    {
        public int Id { get; set; }

        public string Category { get; set; }

        public string Name { get; set; }
    }
}

FoodBasketApp/Models/ErrorViewModel.cs
namespace FoodBasketApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FoodBasketApp/Models/FoodItemsViewModel.cs
using FoodBasketApp.Entities;

namespace FoodBasketApp.Models
{
    public class FoodItemsViewModel
    {
        // A list of FoodItem objects that represent the food items to be shown for the current tab
        public List<FoodItem> ListOfFoodItems { get; set; }

        // An array of strings that represents all the tab names
        public string[] TabNames { get; set; }

        // A string representing the currently active category (tab name)
        public string CurrentlyActive { get; set; }

        // A FoodItem object that represents the newly submitted food item when the user is adding a new food item using the form
        public FoodItem NewFoodItem { get; set; }


    }
}

FoodBasketApp/Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;

using FoodBasketApp.Entities;
using FoodBasketApp.Models;
using FoodBasketApp.Services;
using Microsoft.AspNetCore.Identity;
using System.Security.Cryptography.X509Certificates;

namespace FoodBasketApp.Controllers
{
    public class FoodController : Controller
    {
        public FoodItem emptyFood;
        public string[] arrayCategories = new string[4];

        public FoodController(FoodService foodService)
        {
            _foodService = foodService;
        }

        [HttpGet("/food-items/{category?}")]
        public IActionResult Items(string category)
        {
            List<FoodItem> foodItems;

            if (string.IsNullOrEmpty(category) || category == "All") 
            {
                foodItems = _foodService.GetAllFoodItems();
            }
            else
            {
                foodItems = _foodService.GetFoodItemsByCategory(category);
            }
                
            // Create & initialize a view model:
            FoodItemsViewModel foodItemsViewModel = new FoodItemsViewModel()
            {
                ListOfFoodItems = foodItems,
                CurrentlyActive =  category,
                TabNames = FoodService.FoodCategories,
                NewFoodItem = emptyFood
            };

            return View("Items", foodItemsViewModel);
        }

        [HttpPost("/food-items")]
        public IActionResult AddNewFoodItem(FoodItemsViewModel viewModel)
        {
            _foodService.AddFoodItem(viewModel.NewFoodItem);

            return RedirectToAction("Items", viewModel);
        }

        private FoodService _foodService;
    }
}

FoodBasketApp/Controllers/HomeController.cs
using FoodBasketApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FoodBasketApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FoodBasketApp/Views/Food/Items.cshtml
@using FoodBasketApp.Entities
@model FoodItemsViewModel

@{
    ViewData["Title"] = "Our Food Basket";

    string baseCssClass = "nav-link";
    string cssClass = "";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div>
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Items" asp-route-category="All">All</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Items" asp-route-category="Fruit">Fruit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Items" asp-route-category="Vegetable">Vegetable</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Items" asp-route-category="Meat">Meat</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Items" asp-route-category="Fish">Fish</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Items" asp-route-category="Poultry">Poultry</a>
                    </li>
                    @foreach (string category in Model.TabNames)
                    {
                        if (Model.CurrentlyActive == string.Join(" ", Model.TabNames))
                        {
                            cssClass = baseCssClass + " active";
                        }
                    }
                </ul>
            </div>
    </div>
    <div class="row my-2">
        <div class="col-sm-12 col-md-6">
            @if (Model.ListOfFoodItems.Count > 0)
            {
                <ul>
                    @foreach (FoodItem foodItem in Model.ListOfFoodItems)
                    {
                        <li>@(foodItem.Name)</li>
                    }
                </ul>
            }
            else
            {
                <p>No food to show!</p>
            }
        </div>
        <div class="col-sm-12 col-md-6">
            <h1>Insert a new item</h1>
            <form asp-action="AddNewFoodItem" method="post">
                <div class="form">
                    <label asp-for="NewFoodItem.Name">Name of food</label>
                    <input type="text" asp-for="NewFoodItem.Name" class="form-control" />
                </div>
                <div class="form">
                    <label asp-for="NewFoodItem.Category">Category of food item</label>
                    <select asp-for="NewFoodItem.Category" asp-items="@(new SelectList(FoodBasketApp.Services.FoodService.FoodCategories))" class="form-control">Select a category</select>
                </div>
                <button type="submit" class="btn">Add the food</button>
            </form>
        </div>
    </div>
</div>

FoodBasketApp/Views/Home/Index.cshtml
@model FoodItemsViewModel

@{
    ViewData["Title"] = "Exploring View Models (and attribute routing again)";
}
<h3>The current basket</h3>
<p>
    Check out the current <a asp-controller="Food" asp-action="Items">food basket</a>.
</p>

FoodBasketApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodBasketApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FoodBasketApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FoodBasketApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FoodBasketApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>